# Generated by Django 4.2.1 on 2023-12-04 09:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Films',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название фильма')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Информация о фильме')),
                ('category', models.CharField(max_length=250, verbose_name='Категория фильма')),
                ('rating', models.IntegerField(verbose_name='Рейтинг фильма')),
                ('url_film', models.TextField(blank=True, null=True, verbose_name='Фильм')),
                ('image', models.ImageField(blank=True, null=True, upload_to='img', verbose_name='Изображение')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Фильмы',
            },
        ),
    ]
