# Generated by Django 4.2.1 on 2023-12-05 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='url_film',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на фильм'),
        ),
    ]
